// Generated from pencil-design-system.pen reusable nodes.
export interface RawNodeMeta {
  id: string
  name: string
  exportName: string
  type?: string | null
  width?: number | string | null
  height?: number | string | null
  fill?: unknown
  stroke?: unknown
  strokeWidth?: unknown
  cornerRadius?: unknown
  opacity?: number | null
  layout?: string | null
  slot?: string[] | null
}

export const rawNodes = [
  {
    "id": "OGlde",
    "name": "Btn/DP/CreateTopic/md",
    "exportName": "RawBtnDPCreateTopicMd",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#202020",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "SaJVv",
    "name": "Btn/DP/CreateTopic/hover",
    "exportName": "RawBtnDPCreateTopicHover",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#202020",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": 0.88,
    "layout": null,
    "slot": null
  },
  {
    "id": "zvALt",
    "name": "Btn/DP/CreateTopic/pressed",
    "exportName": "RawBtnDPCreateTopicPressed",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#202020",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": 0.72,
    "layout": null,
    "slot": null
  },
  {
    "id": "AogkE",
    "name": "Btn/DP/CreateTopic/disabled",
    "exportName": "RawBtnDPCreateTopicDisabled",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": 0.6,
    "layout": null,
    "slot": null
  },
  {
    "id": "UR0jn",
    "name": "Btn/DP/AddSource/md",
    "exportName": "RawBtnDPAddSourceMd",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "XvJr2",
    "name": "Btn/DP/AddSource/hover",
    "exportName": "RawBtnDPAddSourceHover",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "F83bOX",
    "name": "Btn/DP/AddSource/disabled",
    "exportName": "RawBtnDPAddSourceDisabled",
    "type": "frame",
    "width": 108,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": 0.45,
    "layout": null,
    "slot": null
  },
  {
    "id": "PcVVK",
    "name": "Btn/DP/SortSelect/md",
    "exportName": "RawBtnDPSortSelectMd",
    "type": "frame",
    "width": 140,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "lYcqD",
    "name": "Btn/DP/SortSelect/hover",
    "exportName": "RawBtnDPSortSelectHover",
    "type": "frame",
    "width": 140,
    "height": 32,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "M4uqlS",
    "name": "Btn/DP/SortSelect/open",
    "exportName": "RawBtnDPSortSelectOpen",
    "type": "frame",
    "width": 140,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "yFiMc",
    "name": "Btn/DP/SortSelect/disabled",
    "exportName": "RawBtnDPSortSelectDisabled",
    "type": "frame",
    "width": 140,
    "height": 32,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": 0.45,
    "layout": null,
    "slot": null
  },
  {
    "id": "FPYLq",
    "name": "Btn/DP/More/md",
    "exportName": "RawBtnDPMoreMd",
    "type": "frame",
    "width": 76,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "iFVuV",
    "name": "Btn/DP/More/hover",
    "exportName": "RawBtnDPMoreHover",
    "type": "frame",
    "width": 76,
    "height": 32,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "KvGLk",
    "name": "Btn/DP/IconOnly/md",
    "exportName": "RawBtnDPIconOnlyMd",
    "type": "frame",
    "width": 32,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "n4OzOf",
    "name": "Btn/DP/IconOnly/hover",
    "exportName": "RawBtnDPIconOnlyHover",
    "type": "frame",
    "width": 32,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "ZIOg7",
    "name": "Btn/DP/IconOnly/disabled",
    "exportName": "RawBtnDPIconOnlyDisabled",
    "type": "frame",
    "width": 32,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": 0.4,
    "layout": null,
    "slot": null
  },
  {
    "id": "VHwVy",
    "name": "DP/Navigation/SideNavItem/md",
    "exportName": "RawDPNavigationSideNavItemMd",
    "type": "frame",
    "width": 228,
    "height": 36,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "RAoyk",
    "name": "DP/Navigation/SideNavItem/hover/md",
    "exportName": "RawDPNavigationSideNavItemHoverMd",
    "type": "frame",
    "width": 228,
    "height": 36,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "eXkOp",
    "name": "DP/Navigation/SideNavItem/focused/md",
    "exportName": "RawDPNavigationSideNavItemFocusedMd",
    "type": "frame",
    "width": 228,
    "height": 36,
    "fill": "#FFFFFF",
    "stroke": "#000000",
    "strokeWidth": 2,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "LedNO",
    "name": "DP/Navigation/SideNavItem/selected/md",
    "exportName": "RawDPNavigationSideNavItemSelectedMd",
    "type": "frame",
    "width": 228,
    "height": 36,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "Zsw33",
    "name": "DP/Navigation/SideNavItem/disabled/md",
    "exportName": "RawDPNavigationSideNavItemDisabledMd",
    "type": "frame",
    "width": 228,
    "height": 36,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 10,
    "opacity": 0.45,
    "layout": null,
    "slot": null
  },
  {
    "id": "xuxyp",
    "name": "DP/Navigation/TabItem/md",
    "exportName": "RawDPNavigationTabItemMd",
    "type": "frame",
    "width": 68,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "mEDLs",
    "name": "DP/Navigation/TabItem/hover/md",
    "exportName": "RawDPNavigationTabItemHoverMd",
    "type": "frame",
    "width": 68,
    "height": 32,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "rmHVf",
    "name": "DP/Navigation/TabItem/inactive/md",
    "exportName": "RawDPNavigationTabItemInactiveMd",
    "type": "frame",
    "width": 68,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "nm7t7",
    "name": "DP/Navigation/TabItem/disabled/md",
    "exportName": "RawDPNavigationTabItemDisabledMd",
    "type": "frame",
    "width": 68,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": 0.45,
    "layout": null,
    "slot": null
  },
  {
    "id": "T9MDAA",
    "name": "DP/Navigation/ViewToggle/card-list",
    "exportName": "RawDPNavigationViewToggleCardList",
    "type": "frame",
    "width": 156,
    "height": 40,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": [
      "xuxyp",
      "rmHVf"
    ]
  },
  {
    "id": "h6RuSr",
    "name": "DP/Navigation/ViewToggle/list-active",
    "exportName": "RawDPNavigationViewToggleListActive",
    "type": "frame",
    "width": 156,
    "height": 40,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": [
      "xuxyp",
      "rmHVf"
    ]
  },
  {
    "id": "VqZzd",
    "name": "DP/Navigation/TabRow",
    "exportName": "RawDPNavigationTabRow",
    "type": "frame",
    "width": null,
    "height": 40,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": [
      "xuxyp",
      "rmHVf"
    ]
  },
  {
    "id": "cBtPL",
    "name": "DP/Navigation/TabRow/with-disabled",
    "exportName": "RawDPNavigationTabRowWithDisabled",
    "type": "frame",
    "width": null,
    "height": 40,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": [
      "xuxyp",
      "rmHVf"
    ]
  },
  {
    "id": "P1Fj1a",
    "name": "DP/Navigation/TabRow/IconOnly/grid-active",
    "exportName": "RawDPNavigationTabRowIconOnlyGridActive",
    "type": "frame",
    "width": 68,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "pHXLu",
    "name": "DP/Navigation/TabRow/IconOnly/list-active",
    "exportName": "RawDPNavigationTabRowIconOnlyListActive",
    "type": "ref",
    "width": 68,
    "height": 32,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "m1Qjq",
    "name": "DP/Navigation/SideNav",
    "exportName": "RawDPNavigationSideNav",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "right": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "GbtYQ",
    "name": "DP/Navigation/SideNav/collapsed",
    "exportName": "RawDPNavigationSideNavCollapsed",
    "type": "frame",
    "width": 60,
    "height": 900,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "right": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "iRrWh",
    "name": "DP/Navigation/Breadcrumb/md",
    "exportName": "RawDPNavigationBreadcrumbMd",
    "type": "frame",
    "width": 360,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": []
  },
  {
    "id": "Ouz6K",
    "name": "DP/Navigation/SideTree/md",
    "exportName": "RawDPNavigationSideTreeMd",
    "type": "frame",
    "width": 260,
    "height": 420,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "treeItem"
    ]
  },
  {
    "id": "Alu21",
    "name": "DP/Navigation/HomeSideNav/CollapseToggle",
    "exportName": "RawDPNavigationHomeSideNavCollapseToggle",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "llICD",
    "name": "DP/Navigation/HomeSideNav/NavWrap",
    "exportName": "RawDPNavigationHomeSideNavNavWrap",
    "type": "frame",
    "width": 228,
    "height": 558,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "U8Katj",
    "name": "DP/Navigation/HomeSideNav/FooterUser",
    "exportName": "RawDPNavigationHomeSideNavFooterUser",
    "type": "frame",
    "width": 228,
    "height": 40,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "PTVmd",
    "name": "DP/Navigation/HomeSideNav/NavWrap/componentized",
    "exportName": "RawDPNavigationHomeSideNavNavWrapComponentized",
    "type": "frame",
    "width": 228,
    "height": 558,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "mqpE1",
    "name": "DP/Navigation/HomeSideNav/FooterUser/componentized",
    "exportName": "RawDPNavigationHomeSideNavFooterUserComponentized",
    "type": "frame",
    "width": 228,
    "height": 40,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "hxSTr",
    "name": "DP/Navigation/SegmentedTabs/text/sm",
    "exportName": "RawDPNavigationSegmentedTabsTextSm",
    "type": "frame",
    "width": 264,
    "height": 28,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "vdyMC",
    "name": "DP/Overlay/MenuItem/md",
    "exportName": "RawDPOverlayMenuItemMd",
    "type": "frame",
    "width": 220,
    "height": 36,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 8,
    "opacity": null,
    "layout": null,
    "slot": []
  },
  {
    "id": "CT2G6",
    "name": "DP/Overlay/MenuItem/hover",
    "exportName": "RawDPOverlayMenuItemHover",
    "type": "frame",
    "width": 220,
    "height": 36,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 8,
    "opacity": null,
    "layout": null,
    "slot": []
  },
  {
    "id": "NmDIh",
    "name": "DP/Overlay/DropdownMenu/sort",
    "exportName": "RawDPOverlayDropdownMenuSort",
    "type": "frame",
    "width": 240,
    "height": 188,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "MenuItem"
    ]
  },
  {
    "id": "r1Onp",
    "name": "DP/Overlay/FilterMenu/type-status",
    "exportName": "RawDPOverlayFilterMenuTypeStatus",
    "type": "frame",
    "width": 300,
    "height": 220,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "Tag3",
      "MenuItem"
    ]
  },
  {
    "id": "w3Jva",
    "name": "DP/Input/Search/md",
    "exportName": "RawDPInputSearchMd",
    "type": "frame",
    "width": 240,
    "height": 32,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "TbDbe",
    "name": "DP/Input/Search/hover/md",
    "exportName": "RawDPInputSearchHoverMd",
    "type": "frame",
    "width": 240,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#2020204D",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "SD3dg",
    "name": "DP/Input/Search/focused/md",
    "exportName": "RawDPInputSearchFocusedMd",
    "type": "frame",
    "width": 240,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "glgRX",
    "name": "DP/Input/Search/error/md",
    "exportName": "RawDPInputSearchErrorMd",
    "type": "frame",
    "width": 240,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#EF4444",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "ZXtxk",
    "name": "DP/Input/Search/disabled/md",
    "exportName": "RawDPInputSearchDisabledMd",
    "type": "frame",
    "width": 240,
    "height": 32,
    "fill": "#F7F9FF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": 0.55,
    "layout": null,
    "slot": null
  },
  {
    "id": "t4oYMt",
    "name": "DP/DataDisplay/Tag3/default/sm",
    "exportName": "RawDPDataDisplayTag3DefaultSm",
    "type": "frame",
    "width": 48,
    "height": 24,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "g8nRP",
    "name": "DP/DataDisplay/Tag3/primary/sm",
    "exportName": "RawDPDataDisplayTag3PrimarySm",
    "type": "frame",
    "width": 48,
    "height": 24,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Lpdyb",
    "name": "DP/DataDisplay/Tag3/hover/sm",
    "exportName": "RawDPDataDisplayTag3HoverSm",
    "type": "frame",
    "width": 48,
    "height": 24,
    "fill": "#F3F4FF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "B1Qql",
    "name": "DP/DataDisplay/Tag3/selected/sm",
    "exportName": "RawDPDataDisplayTag3SelectedSm",
    "type": "frame",
    "width": 60,
    "height": 24,
    "fill": "#F3F4FF",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "n9wT8d",
    "name": "DP/DataDisplay/Tag3/success/sm",
    "exportName": "RawDPDataDisplayTag3SuccessSm",
    "type": "frame",
    "width": 60,
    "height": 24,
    "fill": "#10B9811A",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "ntI0e",
    "name": "DP/DataDisplay/Tag3/warning/sm",
    "exportName": "RawDPDataDisplayTag3WarningSm",
    "type": "frame",
    "width": 60,
    "height": 24,
    "fill": "#F59E0B1A",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "f2Kfm",
    "name": "DP/DataDisplay/Tag3/disabled/sm",
    "exportName": "RawDPDataDisplayTag3DisabledSm",
    "type": "frame",
    "width": 72,
    "height": 24,
    "fill": "#20202014",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "JDei4",
    "name": "DP/Form/FieldLabel/required",
    "exportName": "RawDPFormFieldLabelRequired",
    "type": "frame",
    "width": 120,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "B0RHC",
    "name": "DP/Form/TextInput/md",
    "exportName": "RawDPFormTextInputMd",
    "type": "frame",
    "width": 320,
    "height": 36,
    "fill": "#FFFFFF",
    "stroke": "#E4E6EF",
    "strokeWidth": 1,
    "cornerRadius": 4,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "oqA82",
    "name": "DP/Form/Select/md",
    "exportName": "RawDPFormSelectMd",
    "type": "frame",
    "width": 740,
    "height": 36,
    "fill": "#FFFFFF",
    "stroke": "#E4E6EF",
    "strokeWidth": 1,
    "cornerRadius": 6,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "PivUX",
    "name": "DP/Form/TextArea/md",
    "exportName": "RawDPFormTextAreaMd",
    "type": "frame",
    "width": 740,
    "height": 68,
    "fill": "#FFFFFF",
    "stroke": "#E4E6EF",
    "strokeWidth": 1,
    "cornerRadius": 6,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "AMH6R",
    "name": "DP/Form/PermissionTargetCard",
    "exportName": "RawDPFormPermissionTargetCard",
    "type": "frame",
    "width": 740,
    "height": 72,
    "fill": "#F7F8FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 8,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "u3OCgq",
    "name": "DP/Form/PermissionOptionCard/selected",
    "exportName": "RawDPFormPermissionOptionCardSelected",
    "type": "frame",
    "width": 740,
    "height": 96,
    "fill": "#F7F8FF",
    "stroke": "#6E77FF",
    "strokeWidth": 1.5,
    "cornerRadius": 8,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "dWbyY",
    "name": "DP/Form/PermissionOptionCard/default",
    "exportName": "RawDPFormPermissionOptionCardDefault",
    "type": "frame",
    "width": 740,
    "height": 96,
    "fill": "#F7F8FF",
    "stroke": "#E4E6EF",
    "strokeWidth": 1,
    "cornerRadius": 8,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "p0Zzv",
    "name": "DP/Form/AgreementRow/md",
    "exportName": "RawDPFormAgreementRowMd",
    "type": "frame",
    "width": 240,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "fkiGc",
    "name": "Btn/DP/FormPrimary/sm",
    "exportName": "RawBtnDPFormPrimarySm",
    "type": "frame",
    "width": 64,
    "height": 32,
    "fill": "#202020",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "D9kbVP",
    "name": "Btn/DP/FormSecondary/sm",
    "exportName": "RawBtnDPFormSecondarySm",
    "type": "frame",
    "width": 64,
    "height": 32,
    "fill": "#FFFFFF",
    "stroke": "#E4E6EF",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "H25lpe",
    "name": "DP/Form/DialogHeader/applyPermission",
    "exportName": "RawDPFormDialogHeaderApplyPermission",
    "type": "frame",
    "width": 740,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "mO5XK",
    "name": "DP/Form/ApplicantInfo/md",
    "exportName": "RawDPFormApplicantInfoMd",
    "type": "frame",
    "width": 180,
    "height": 56,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Zwe8U",
    "name": "DP/Content/TopicCard/md",
    "exportName": "RawDPContentTopicCardMd",
    "type": "frame",
    "width": 240,
    "height": 160,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "KdrBg",
    "name": "DP/Content/RecentAccessCard/md",
    "exportName": "RawDPContentRecentAccessCardMd",
    "type": "frame",
    "width": 304,
    "height": 146,
    "fill": "#FFFFFF",
    "stroke": "#DEE0ED",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "vDMVt",
    "name": "DP/Content/RecentAccessCard/hover/md",
    "exportName": "RawDPContentRecentAccessCardHoverMd",
    "type": "frame",
    "width": 304,
    "height": 146,
    "fill": "#FFFFFF",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "IEOSJ",
    "name": "DP/Content/ListRow/md",
    "exportName": "RawDPContentListRowMd",
    "type": "frame",
    "width": 760,
    "height": 64,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": 12,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "H7snj",
    "name": "DP/Content/ListRow/selected/md",
    "exportName": "RawDPContentListRowSelectedMd",
    "type": "frame",
    "width": 760,
    "height": 64,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "fVWeO",
    "name": "DP/Feedback/EmptyState/md",
    "exportName": "RawDPFeedbackEmptyStateMd",
    "type": "frame",
    "width": 320,
    "height": null,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "UR0jn",
      "OGlde"
    ]
  },
  {
    "id": "x7Ml6X",
    "name": "DP/Feedback/LockedContent/md",
    "exportName": "RawDPFeedbackLockedContentMd",
    "type": "frame",
    "width": 360,
    "height": 220,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 18,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "UR0jn",
      "KvGLk"
    ]
  },
  {
    "id": "Nz3Qm",
    "name": "DP/Feedback/LockedContent/inline",
    "exportName": "RawDPFeedbackLockedContentInline",
    "type": "frame",
    "width": 520,
    "height": 64,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": [
      "KvGLk",
      "UR0jn"
    ]
  },
  {
    "id": "zyqLg",
    "name": "DP/DataDisplay/MetricMiniCard/md",
    "exportName": "RawDPDataDisplayMetricMiniCardMd",
    "type": "frame",
    "width": 160,
    "height": 92,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "icon",
      "trend"
    ]
  },
  {
    "id": "IdRDa",
    "name": "DP/DataDisplay/MetricMiniCard/muted",
    "exportName": "RawDPDataDisplayMetricMiniCardMuted",
    "type": "frame",
    "width": 160,
    "height": 92,
    "fill": "#F7F9FF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "icon",
      "trend"
    ]
  },
  {
    "id": "IKsVk",
    "name": "DP/Content/CoverThumbnail/md",
    "exportName": "RawDPContentCoverThumbnailMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#E0D9FF",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "none",
    "slot": []
  },
  {
    "id": "auA0l",
    "name": "DP/Content/CoverThumbnail/warm",
    "exportName": "RawDPContentCoverThumbnailWarm",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#F1E9DD",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "none",
    "slot": []
  },
  {
    "id": "U0job",
    "name": "DP/Content/CoverThumbnail/hover",
    "exportName": "RawDPContentCoverThumbnailHover",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#E0D9FF",
    "stroke": "#202020",
    "strokeWidth": 1.5,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "none",
    "slot": []
  },
  {
    "id": "Y0lfk",
    "name": "DP/Content/TopicTile/md",
    "exportName": "RawDPContentTopicTileMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#E4EBFC",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "g4YeS",
    "name": "DP/Content/TopicTile/hover/md",
    "exportName": "RawDPContentTopicTileHoverMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#E4EBFC",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "xmlTd",
    "name": "DP/Content/TopicTile/selected/md",
    "exportName": "RawDPContentTopicTileSelectedMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#F3F4FF",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "rb0TC",
    "name": "DP/Content/TopicTile/disabled/md",
    "exportName": "RawDPContentTopicTileDisabledMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#F7F9FF",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": 0.45,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "DtaqM",
    "name": "DP/Content/FolderTile/md",
    "exportName": "RawDPContentFolderTileMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#F1E9DD",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "W1mVDw",
    "name": "DP/Content/FolderTile/hover/md",
    "exportName": "RawDPContentFolderTileHoverMd",
    "type": "frame",
    "width": 184,
    "height": 104,
    "fill": "#F1E9DD",
    "stroke": "#6E77FF",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "bahso",
    "name": "DP/Home/HeroBanner",
    "exportName": "RawDPHomeHeroBanner",
    "type": "frame",
    "width": 1264,
    "height": 160,
    "fill": "#E0D9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": null,
    "slot": [
      "OGlde",
      "UR0jn"
    ]
  },
  {
    "id": "vpwA7",
    "name": "DP/Content/HomeHeroBanner/md",
    "exportName": "RawDPContentHomeHeroBannerMd",
    "type": "frame",
    "width": 1110,
    "height": 148,
    "fill": "#E0D9FF",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 24,
    "opacity": null,
    "layout": "none",
    "slot": [
      "media"
    ]
  },
  {
    "id": "u13hG",
    "name": "DP/Layout/HomeSectionHeader/default",
    "exportName": "RawDPLayoutHomeSectionHeaderDefault",
    "type": "frame",
    "width": 1110,
    "height": 40,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": [
      "sort",
      "more"
    ]
  },
  {
    "id": "P58KFs",
    "name": "DP/Content/HomeTopicCard/md",
    "exportName": "RawDPContentHomeTopicCardMd",
    "type": "frame",
    "width": 204,
    "height": 108,
    "fill": "#E4EBFC",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "none",
    "slot": [
      "media"
    ]
  },
  {
    "id": "pczao",
    "name": "DP/Content/HomeTopicCard/folder",
    "exportName": "RawDPContentHomeTopicCardFolder",
    "type": "frame",
    "width": 204,
    "height": 108,
    "fill": "#E4EBFC",
    "stroke": "#2020200F",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "none",
    "slot": [
      "avatars"
    ]
  },
  {
    "id": "w5yXC",
    "name": "DP/Table/ColumnHeader/md",
    "exportName": "RawDPTableColumnHeaderMd",
    "type": "frame",
    "width": 160,
    "height": 36,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": []
  },
  {
    "id": "lyS8k",
    "name": "DP/Table/ColumnHeader/right/md",
    "exportName": "RawDPTableColumnHeaderRightMd",
    "type": "frame",
    "width": 120,
    "height": 36,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": []
  },
  {
    "id": "m070iW",
    "name": "DP/Table/ColumnHeader/hover/md",
    "exportName": "RawDPTableColumnHeaderHoverMd",
    "type": "frame",
    "width": 160,
    "height": 36,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "eN1IG",
    "name": "DP/Table/ColumnHeader/sorted/md",
    "exportName": "RawDPTableColumnHeaderSortedMd",
    "type": "frame",
    "width": 160,
    "height": 36,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "p6MPAg",
    "name": "DP/Table/SortIndicator/desc",
    "exportName": "RawDPTableSortIndicatorDesc",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 6,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "aSd0C",
    "name": "DP/Table/SortIndicator/asc",
    "exportName": "RawDPTableSortIndicatorAsc",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 6,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "t6q720",
    "name": "DP/Table/SortIndicator/inactive",
    "exportName": "RawDPTableSortIndicatorInactive",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 6,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "zSFxC",
    "name": "DP/Table/TableHeader/md",
    "exportName": "RawDPTableTableHeaderMd",
    "type": "frame",
    "width": 960,
    "height": 36,
    "fill": "#F7F9FF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": [
      12,
      12,
      0,
      0
    ],
    "opacity": null,
    "layout": null,
    "slot": [
      "w5yXC",
      "lyS8k"
    ]
  },
  {
    "id": "n8jMH",
    "name": "DP/Table/TableRow/md",
    "exportName": "RawDPTableTableRowMd",
    "type": "frame",
    "width": 960,
    "height": 56,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "g5r9g",
    "name": "DP/Table/TableRow/hover/md",
    "exportName": "RawDPTableTableRowHoverMd",
    "type": "frame",
    "width": 960,
    "height": 56,
    "fill": "#F7F9FF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "unLA0",
    "name": "DP/Table/TableRow/selected/md",
    "exportName": "RawDPTableTableRowSelectedMd",
    "type": "frame",
    "width": 960,
    "height": 56,
    "fill": "#F3F4FF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "G5izK",
    "name": "DP/Table/TableRow/disabled/md",
    "exportName": "RawDPTableTableRowDisabledMd",
    "type": "frame",
    "width": 960,
    "height": 56,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": 0.45,
    "layout": null,
    "slot": null
  },
  {
    "id": "TUDgg",
    "name": "DP/Table/ActionCell/md",
    "exportName": "RawDPTableActionCellMd",
    "type": "frame",
    "width": 100,
    "height": 40,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": [
      "KvGLk",
      "FPYLq"
    ]
  },
  {
    "id": "C49O1",
    "name": "DP/Table/ActionCell/hover",
    "exportName": "RawDPTableActionCellHover",
    "type": "frame",
    "width": 100,
    "height": 40,
    "fill": "#F3F4FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "dLGfm",
    "name": "DP/Table/ActionCell/focused",
    "exportName": "RawDPTableActionCellFocused",
    "type": "frame",
    "width": 100,
    "height": 40,
    "fill": "#FFFFFF",
    "stroke": "#000000",
    "strokeWidth": 2,
    "cornerRadius": 10,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "Zy9ps",
    "name": "DP/Table/ActionCell/compact",
    "exportName": "RawDPTableActionCellCompact",
    "type": "frame",
    "width": 72,
    "height": 40,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": [
      "KvGLk",
      "FPYLq"
    ]
  },
  {
    "id": "Z9NflL",
    "name": "DP/Table/EmptyRow/md",
    "exportName": "RawDPTableEmptyRowMd",
    "type": "frame",
    "width": 960,
    "height": 188,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": []
  },
  {
    "id": "ORKSp",
    "name": "DP/Table/LoadingRow/md",
    "exportName": "RawDPTableLoadingRowMd",
    "type": "frame",
    "width": 960,
    "height": 168,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": []
  },
  {
    "id": "RZAdy",
    "name": "DP/Table/TableContainer/default",
    "exportName": "RawDPTableTableContainerDefault",
    "type": "frame",
    "width": 960,
    "height": 316,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "zSFxC",
      "n8jMH",
      "g5r9g",
      "unLA0",
      "G5izK"
    ]
  },
  {
    "id": "wUl3j",
    "name": "DP/Table/TableContainer/empty",
    "exportName": "RawDPTableTableContainerEmpty",
    "type": "frame",
    "width": 960,
    "height": 224,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "zSFxC",
      "Z9NflL"
    ]
  },
  {
    "id": "V9TBIJ",
    "name": "DP/Table/TableContainer/loading",
    "exportName": "RawDPTableTableContainerLoading",
    "type": "frame",
    "width": 960,
    "height": 204,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "zSFxC",
      "ORKSp"
    ]
  },
  {
    "id": "NMDsu",
    "name": "DP/Layout/SectionHeader",
    "exportName": "RawDPLayoutSectionHeader",
    "type": "frame",
    "width": 1264,
    "height": null,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": [
      "w3Jva",
      "xuxyp",
      "UR0jn",
      "OGlde",
      "PcVVK",
      "FPYLq"
    ]
  },
  {
    "id": "OzK0y",
    "name": "DP/Layout/TopNav",
    "exportName": "RawDPLayoutTopNav",
    "type": "frame",
    "width": 1600,
    "height": 58,
    "fill": "#FFFFFF",
    "stroke": "#EAECF5",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": [
      "w3Jva",
      "KvGLk",
      "OGlde",
      "UR0jn"
    ]
  },
  {
    "id": "r5enCu",
    "name": "DP/Layout/PageHeader/default",
    "exportName": "RawDPLayoutPageHeaderDefault",
    "type": "frame",
    "width": 1184,
    "height": 132,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "breadcrumb",
      "OGlde",
      "UR0jn"
    ]
  },
  {
    "id": "GT1xU",
    "name": "DP/Layout/PageHeader/compact",
    "exportName": "RawDPLayoutPageHeaderCompact",
    "type": "frame",
    "width": 760,
    "height": 88,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": [
      "breadcrumb",
      "OGlde"
    ]
  },
  {
    "id": "UGApo",
    "name": "DP/Scenario/LibraryToolbar/default",
    "exportName": "RawDPScenarioLibraryToolbarDefault",
    "type": "frame",
    "width": 1184,
    "height": 64,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": null,
    "slot": [
      "w3Jva",
      "PcVVK",
      "UR0jn",
      "OGlde",
      "FPYLq"
    ]
  },
  {
    "id": "kOqne",
    "name": "DP/Scenario/LibraryToolbar/compact",
    "exportName": "RawDPScenarioLibraryToolbarCompact",
    "type": "frame",
    "width": 760,
    "height": 56,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": [
      "w3Jva",
      "PcVVK",
      "OGlde"
    ]
  },
  {
    "id": "v1C0r2",
    "name": "DP/Scenario/TopicGallerySection/cards",
    "exportName": "RawDPScenarioTopicGallerySectionCards",
    "type": "frame",
    "width": 1264,
    "height": 392,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "NMDsu",
      "I6OeP"
    ]
  },
  {
    "id": "K4fCxW",
    "name": "DP/Scenario/TopicTableSection/table",
    "exportName": "RawDPScenarioTopicTableSectionTable",
    "type": "frame",
    "width": 1264,
    "height": 480,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "NMDsu",
      "UGApo",
      "RZAdy"
    ]
  },
  {
    "id": "I6OeP",
    "name": "DP/Layout/CardGrid/4col",
    "exportName": "RawDPLayoutCardGrid4col",
    "type": "frame",
    "width": 784,
    "height": null,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "Y0lfk",
      "DtaqM",
      "xmlTd",
      "Zwe8U",
      "KdrBg"
    ]
  },
  {
    "id": "g3zJ8",
    "name": "DP/Layout/AppShell",
    "exportName": "RawDPLayoutAppShell",
    "type": "frame",
    "width": 1600,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "MFbHG",
    "name": "DP/Layout/AppShell/collapsedNav",
    "exportName": "RawDPLayoutAppShellCollapsedNav",
    "type": "frame",
    "width": 1600,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "PgT7W",
    "name": "DP/Content/ArticleHero/md",
    "exportName": "RawDPContentArticleHeroMd",
    "type": "frame",
    "width": 720,
    "height": 260,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 18,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "cover",
      "actions"
    ]
  },
  {
    "id": "H9HzT",
    "name": "DP/Content/RichTextBlock/md",
    "exportName": "RawDPContentRichTextBlockMd",
    "type": "frame",
    "width": 720,
    "height": 300,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "paragraph",
      "list"
    ]
  },
  {
    "id": "zs7Kb",
    "name": "DP/Layout/RightInfoPanel/md",
    "exportName": "RawDPLayoutRightInfoPanelMd",
    "type": "frame",
    "width": 300,
    "height": 420,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 16,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "Tag3",
      "actions"
    ]
  },
  {
    "id": "Xs48N",
    "name": "DP/AI/AskBox/md",
    "exportName": "RawDPAIAskBoxMd",
    "type": "frame",
    "width": 720,
    "height": 132,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 18,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "input",
      "actions"
    ]
  },
  {
    "id": "aX3F4",
    "name": "DP/AI/AnswerBlock/loading",
    "exportName": "RawDPAIAnswerBlockLoading",
    "type": "frame",
    "width": 720,
    "height": 180,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 18,
    "opacity": null,
    "layout": "vertical",
    "slot": []
  },
  {
    "id": "q1e8U",
    "name": "DP/Brand/DataPocketLogo/md",
    "exportName": "RawDPBrandDataPocketLogoMd",
    "type": "frame",
    "width": 148,
    "height": 39,
    "fill": {
      "enabled": true,
      "mode": "fit",
      "type": "image",
      "url": "pic/logo.png"
    },
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "fxMyB",
    "name": "DP/Navigation/HomeSideNav/Divider",
    "exportName": "RawDPNavigationHomeSideNavDivider",
    "type": "frame",
    "width": 228,
    "height": 1,
    "fill": "#2020200F",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "TLQuT",
    "name": "DP/Navigation/HomeSideNav/SectionTitle",
    "exportName": "RawDPNavigationHomeSideNavSectionTitle",
    "type": "text",
    "width": 228,
    "height": null,
    "fill": "#20202099",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "C3ZXP",
    "name": "DP/Navigation/HomeSideNav/FooterUserInfo",
    "exportName": "RawDPNavigationHomeSideNavFooterUserInfo",
    "type": "frame",
    "width": 85,
    "height": 28,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "qy9Yx",
    "name": "DP/Navigation/HomeSideNav/FooterActions",
    "exportName": "RawDPNavigationHomeSideNavFooterActions",
    "type": "frame",
    "width": 72,
    "height": 16,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "ukjm0",
    "name": "DP/Layout/HomePageTitle/default",
    "exportName": "RawDPLayoutHomePageTitleDefault",
    "type": "text",
    "width": null,
    "height": null,
    "fill": "#202020",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "eDIOC",
    "name": "DP/Layout/HomeTopActions/extracted",
    "exportName": "RawDPLayoutHomeTopActionsExtracted",
    "type": "frame",
    "width": 448,
    "height": 32,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "FbksV",
    "name": "DP/Layout/HomeTopBar/componentized",
    "exportName": "RawDPLayoutHomeTopBarComponentized",
    "type": "frame",
    "width": 1260,
    "height": 44,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Yq6rJ",
    "name": "DP/Navigation/HomeSideNav/NavStage",
    "exportName": "RawDPNavigationHomeSideNavNavStage",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "tSLc2",
    "name": "DP/Navigation/HomeSideNav/NavStage/componentized",
    "exportName": "RawDPNavigationHomeSideNavNavStageComponentized",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Cf4JO",
    "name": "DP/Navigation/HomeSideNav/Background",
    "exportName": "RawDPNavigationHomeSideNavBackground",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": {
      "colors": [
        {
          "color": "#E9E6FF",
          "position": 0
        },
        {
          "color": "#F2F0FF",
          "position": 0.18
        },
        {
          "color": "#F7F8FF",
          "position": 0.36
        },
        {
          "color": "#FAFBFF",
          "position": 0.58
        },
        {
          "color": "#F7F9FF",
          "position": 1
        }
      ],
      "enabled": true,
      "gradientType": "linear",
      "rotation": 180,
      "size": {
        "height": 1
      },
      "type": "gradient"
    },
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "MFeZC",
    "name": "DP/Navigation/HomeSideNav/NavStage/fully-componentized",
    "exportName": "RawDPNavigationHomeSideNavNavStageFullyComponentized",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "DErAm",
    "name": "DP/Scenario/HomeFollowSection/cards",
    "exportName": "RawDPScenarioHomeFollowSectionCards",
    "type": "frame",
    "width": 1260,
    "height": null,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "MR87f",
    "name": "DP/Scenario/HomeContentSlot/default",
    "exportName": "RawDPScenarioHomeContentSlotDefault",
    "type": "frame",
    "width": 1260,
    "height": 760,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "rDSus",
    "name": "DP/Layout/HomeAppShell/md",
    "exportName": "RawDPLayoutHomeAppShellMd",
    "type": "frame",
    "width": 1480,
    "height": 900,
    "fill": "#F5F7FB",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "DuxXY",
    "name": "DP/Layout/HomeTopBar/default",
    "exportName": "RawDPLayoutHomeTopBarDefault",
    "type": "frame",
    "width": 1260,
    "height": 44,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "t9ojS0",
    "name": "DP/Layout/HomeContentSlot/empty",
    "exportName": "RawDPLayoutHomeContentSlotEmpty",
    "type": "frame",
    "width": 1260,
    "height": 760,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "fC8k3",
    "name": "DP/Layout/HomeMainPanel/1340/content",
    "exportName": "RawDPLayoutHomeMainPanel1340Content",
    "type": "frame",
    "width": 1316,
    "height": 876,
    "fill": "#FFFFFF",
    "stroke": "#EDF0F6",
    "strokeWidth": {
      "left": 1
    },
    "cornerRadius": 24,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "t9PnIa",
    "name": "DP/AI/AnswerBlock/md",
    "exportName": "RawDPAIAnswerBlockMd",
    "type": "frame",
    "width": 720,
    "height": 300,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": 1,
    "cornerRadius": 18,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "actions",
      "sources"
    ]
  },
  {
    "id": "HvJtL",
    "name": "DP/AI/AskBox/focused",
    "exportName": "RawDPAIAskBoxFocused",
    "type": "frame",
    "width": 720,
    "height": 132,
    "fill": "#FFFFFF",
    "stroke": "#202020",
    "strokeWidth": 1.5,
    "cornerRadius": 18,
    "opacity": null,
    "layout": "vertical",
    "slot": [
      "input",
      "actions"
    ]
  },
  {
    "id": "aqfkD",
    "name": "DP2/Foundation/Surface/Card/elevated",
    "exportName": "RawDP2FoundationSurfaceCardElevated",
    "type": "frame",
    "width": 160,
    "height": 104,
    "fill": "#FFFFFF",
    "stroke": "#FFFFFF99",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "pThRc",
    "name": "DP2/Foundation/Surface/Card/subtle",
    "exportName": "RawDP2FoundationSurfaceCardSubtle",
    "type": "frame",
    "width": 160,
    "height": 104,
    "fill": "#FFFFFF",
    "stroke": "#E8EAF166",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "ZeH54",
    "name": "DP2/Layout/FlexSpacer",
    "exportName": "RawDP2LayoutFlexSpacer",
    "type": "frame",
    "width": 120,
    "height": 40,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "mZ0pa",
    "name": "DP2/Navigation/Breadcrumb/compact",
    "exportName": "RawDP2NavigationBreadcrumbCompact",
    "type": "frame",
    "width": 240,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "OZOxx",
    "name": "DP2/DataDisplay/Tag/keyword/sm",
    "exportName": "RawDP2DataDisplayTagKeywordSm",
    "type": "frame",
    "width": 60,
    "height": 24,
    "fill": "#FFFFFF",
    "stroke": "#E8EAF1",
    "strokeWidth": 1,
    "cornerRadius": 4,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "o7Q4Wt",
    "name": "DP2/DataDisplay/KeywordTag/soft/sm",
    "exportName": "RawDP2DataDisplayKeywordTagSoftSm",
    "type": "frame",
    "width": 64,
    "height": 24,
    "fill": "#F8F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 8,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "pZqMi",
    "name": "DP2/Navigation/UnderlineTab/active/sm",
    "exportName": "RawDP2NavigationUnderlineTabActiveSm",
    "type": "frame",
    "width": 56,
    "height": 32,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "tlnbp",
    "name": "DP2/Navigation/UnderlineTab/inactive/sm",
    "exportName": "RawDP2NavigationUnderlineTabInactiveSm",
    "type": "frame",
    "width": 56,
    "height": 32,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Q9A10L",
    "name": "DP2/Button/IconOnly/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlyGhostSm",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "agx7b",
    "name": "DP2/Button/IconOnly/search/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlySearchGhostSm",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "UsnUE",
    "name": "DP2/Button/IconOnly/panel-right/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlyPanelRightGhostSm",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 14,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "u8gWRX",
    "name": "DP2/Button/IconOnly/history/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlyHistoryGhostSm",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "y6a6d",
    "name": "DP2/Button/IconOnly/new-chat/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlyNewChatGhostSm",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "qXRmt",
    "name": "DP2/DataDisplay/ChartBar/vertical",
    "exportName": "RawDP2DataDisplayChartBarVertical",
    "type": "frame",
    "width": 32,
    "height": 96,
    "fill": "#3376FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": [
      3,
      3,
      0,
      0
    ],
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "AZKhg",
    "name": "DP2/DataDisplay/ChartAxisLabel",
    "exportName": "RawDP2DataDisplayChartAxisLabel",
    "type": "text",
    "width": null,
    "height": null,
    "fill": "#20202099",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "dliqp",
    "name": "DP2/DataDisplay/ChartLegendItem",
    "exportName": "RawDP2DataDisplayChartLegendItem",
    "type": "frame",
    "width": 80,
    "height": 20,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "yvDfL",
    "name": "DP2/Detail/Source/HeaderBar",
    "exportName": "RawDP2DetailSourceHeaderBar",
    "type": "frame",
    "width": 520,
    "height": 48,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "x1Gkm",
    "name": "DP2/Detail/Source/GuideCard",
    "exportName": "RawDP2DetailSourceGuideCard",
    "type": "frame",
    "width": 520,
    "height": 170,
    "fill": "#F5F4FF",
    "stroke": "#FFFFFF66",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "T5RUmx",
    "name": "DP2/Detail/Source/DescriptionCard",
    "exportName": "RawDP2DetailSourceDescriptionCard",
    "type": "frame",
    "width": 448,
    "height": 116,
    "fill": "#FFFFFF",
    "stroke": "#E8EAF166",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "x0jC34",
    "name": "DP2/Detail/Source/NewUserDashboard",
    "exportName": "RawDP2DetailSourceNewUserDashboard",
    "type": "frame",
    "width": 480,
    "height": 618,
    "fill": "#F8F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "stG6B",
    "name": "DP2/Detail/Source/ReferencePanel",
    "exportName": "RawDP2DetailSourceReferencePanel",
    "type": "frame",
    "width": 488,
    "height": 260,
    "fill": "#FFFFFF",
    "stroke": "#E8EAF166",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "HQI3p",
    "name": "DP2/DataDisplay/BarChartPlot/basic",
    "exportName": "RawDP2DataDisplayBarChartPlotBasic",
    "type": "frame",
    "width": 416,
    "height": 250,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "aDfR2",
    "name": "DP2/DataDisplay/BarChartCard/source",
    "exportName": "RawDP2DataDisplayBarChartCardSource",
    "type": "frame",
    "width": 448,
    "height": 350,
    "fill": "#FFFFFF",
    "stroke": "#E8EAF166",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "f8rCJW",
    "name": "DP2/Detail/Source/HeaderBar/title",
    "exportName": "RawDP2DetailSourceHeaderBarTitle",
    "type": "frame",
    "width": 392,
    "height": 44,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "Mo5NG",
    "name": "DP2/Detail/Source/TreeRow",
    "exportName": "RawDP2DetailSourceTreeRow",
    "type": "frame",
    "width": 364,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "BqAxp",
    "name": "DP2/Detail/Source/TreeList/target-2",
    "exportName": "RawDP2DetailSourceTreeListTarget2",
    "type": "frame",
    "width": 392,
    "height": 836,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "NFT6V",
    "name": "DP2/Detail/Center/HeroCover",
    "exportName": "RawDP2DetailCenterHeroCover",
    "type": "frame",
    "width": 640,
    "height": 104,
    "fill": {
      "colors": [
        {
          "color": "#EAF0FF",
          "position": 0
        },
        {
          "color": "#F6EAFE",
          "position": 0.42
        },
        {
          "color": "#B9E2FF",
          "position": 0.72
        },
        {
          "color": "#FFFFFF",
          "position": 1
        }
      ],
      "enabled": true,
      "gradientType": "linear",
      "rotation": -110,
      "size": {
        "height": 1
      },
      "type": "gradient"
    },
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "N1UYQ",
    "name": "DP2/Detail/Center/SummaryBlock",
    "exportName": "RawDP2DetailCenterSummaryBlock",
    "type": "frame",
    "width": 640,
    "height": 170,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "WRmX7",
    "name": "DP2/Detail/Center/KeywordRow",
    "exportName": "RawDP2DetailCenterKeywordRow",
    "type": "frame",
    "width": 240,
    "height": 24,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "sepp4",
    "name": "DP2/Detail/Center/SuggestionItem",
    "exportName": "RawDP2DetailCenterSuggestionItem",
    "type": "frame",
    "width": 560,
    "height": 30,
    "fill": "#F8F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 8,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "RVo8w",
    "name": "DP2/Detail/Center/SuggestionList",
    "exportName": "RawDP2DetailCenterSuggestionList",
    "type": "frame",
    "width": 560,
    "height": 112,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "XFZYW",
    "name": "DP2/Detail/Center/TopBarActions",
    "exportName": "RawDP2DetailCenterTopBarActions",
    "type": "frame",
    "width": 64,
    "height": 28,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "k4oxh1",
    "name": "DP2/AI/DialogInput/PromptArea",
    "exportName": "RawDP2AIDialogInputPromptArea",
    "type": "frame",
    "width": 612,
    "height": 80,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "SkOMO",
    "name": "DP2/AI/DialogInput/QuickMode",
    "exportName": "RawDP2AIDialogInputQuickMode",
    "type": "frame",
    "width": 108,
    "height": 28,
    "fill": "#F8F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "i8pFV",
    "name": "DP2/AI/DialogInput/SendCircle/disabled",
    "exportName": "RawDP2AIDialogInputSendCircleDisabled",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#D9DDE8",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "hEb2C",
    "name": "DP2/AI/DialogInput/SourceSend",
    "exportName": "RawDP2AIDialogInputSourceSend",
    "type": "frame",
    "width": 132,
    "height": 28,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "ZaZ4Y",
    "name": "DP2/AI/DialogInput/Footer",
    "exportName": "RawDP2AIDialogInputFooter",
    "type": "frame",
    "width": 612,
    "height": 30,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "gwygO",
    "name": "DP2/Detail/Center/TopBar",
    "exportName": "RawDP2DetailCenterTopBar",
    "type": "frame",
    "width": 672,
    "height": 48,
    "fill": "#FFFFFF",
    "stroke": "#2020201A",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "lADuh",
    "name": "DP2/Detail/Center/HeroHeader",
    "exportName": "RawDP2DetailCenterHeroHeader",
    "type": "frame",
    "width": 672,
    "height": 118,
    "fill": "#FFFFFF",
    "stroke": "#00000000",
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "FSQyv",
    "name": "DP2/Detail/Center/ArticleBody",
    "exportName": "RawDP2DetailCenterArticleBody",
    "type": "frame",
    "width": 672,
    "height": 526,
    "fill": "#FFFFFF",
    "stroke": "#00000000",
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "OuHtY",
    "name": "DP2/AI/DialogInput/fixedBottom",
    "exportName": "RawDP2AIDialogInputFixedBottom",
    "type": "frame",
    "width": 672,
    "height": 150,
    "fill": "#FFFFFF",
    "stroke": "#E8EAF166",
    "strokeWidth": 1,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "B21D1c",
    "name": "DP2/AI/DialogInput/Dock",
    "exportName": "RawDP2AIDialogInputDock",
    "type": "frame",
    "width": 672,
    "height": 166,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "WspTg",
    "name": "DP2/Detail/Center/TopBarTitle",
    "exportName": "RawDP2DetailCenterTopBarTitle",
    "type": "frame",
    "width": 80,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "u4A7Us",
    "name": "DP2/Detail/Center/HeroCover/target-2",
    "exportName": "RawDP2DetailCenterHeroCoverTarget2",
    "type": "frame",
    "width": 640,
    "height": 104,
    "fill": {
      "colors": [
        {
          "color": "#EAF0FF",
          "position": 0
        },
        {
          "color": "#F6EAFE",
          "position": 0.42
        },
        {
          "color": "#B9E2FF",
          "position": 0.72
        },
        {
          "color": "#FFFFFF",
          "position": 1
        }
      ],
      "enabled": true,
      "gradientType": "linear",
      "rotation": -110,
      "size": {
        "height": 1
      },
      "type": "gradient"
    },
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "DqFjl",
    "name": "DP2/Detail/Center/SummaryBlock/target-2",
    "exportName": "RawDP2DetailCenterSummaryBlockTarget2",
    "type": "frame",
    "width": 736,
    "height": 196,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "n4uGx",
    "name": "DP2/Detail/Center/ArticleBody/target-2",
    "exportName": "RawDP2DetailCenterArticleBodyTarget2",
    "type": "frame",
    "width": 768,
    "height": 502,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "hEpa2",
    "name": "DP2/Detail/Center/HeroHeader/target-2",
    "exportName": "RawDP2DetailCenterHeroHeaderTarget2",
    "type": "frame",
    "width": 672,
    "height": 118,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "fgeOy",
    "name": "DP2/Scenario/SourcePanel/target-1",
    "exportName": "RawDP2ScenarioSourcePanelTarget1",
    "type": "frame",
    "width": 512,
    "height": 884,
    "fill": "#FFFFFF",
    "stroke": "#FFFFFF99",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "Kt6IK",
    "name": "DP2/Scenario/CenterDialog/target-1",
    "exportName": "RawDP2ScenarioCenterDialogTarget1",
    "type": "frame",
    "width": 672,
    "height": 884,
    "fill": "#FFFFFF",
    "stroke": "#FFFFFF99",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "GMln2",
    "name": "DP2/Scenario/RightStudioPanel/target-1",
    "exportName": "RawDP2ScenarioRightStudioPanelTarget1",
    "type": "frame",
    "width": 352,
    "height": 884,
    "fill": "#FFFFFF",
    "stroke": "#FFFFFF99",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "kAWGn",
    "name": "DP2/Scenario/SourcePanel/Content",
    "exportName": "RawDP2ScenarioSourcePanelContent",
    "type": "frame",
    "width": 512,
    "height": 836,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "uCstR",
    "name": "DP2/Scenario/SourcePanel/target-2",
    "exportName": "RawDP2ScenarioSourcePanelTarget2",
    "type": "frame",
    "width": 512,
    "height": 884,
    "fill": "#FFFFFF",
    "stroke": "#FFFFFF99",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "jBi4l",
    "name": "DP2/Scenario/CenterDialog/target-2",
    "exportName": "RawDP2ScenarioCenterDialogTarget2",
    "type": "frame",
    "width": 768,
    "height": 884,
    "fill": "#FFFFFF",
    "stroke": "#FFFFFF99",
    "strokeWidth": 1,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "S0cHjR",
    "name": "DP2/Scenario/FullLayout/target-2",
    "exportName": "RawDP2ScenarioFullLayoutTarget2",
    "type": "frame",
    "width": 1600,
    "height": 900,
    "fill": {
      "colors": [
        {
          "color": "#E4EBFC",
          "position": 0
        },
        {
          "color": "#FFFFFF",
          "position": 1
        }
      ],
      "enabled": true,
      "gradientType": "linear",
      "rotation": -135,
      "size": {
        "height": 1
      },
      "type": "gradient"
    },
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "h4EkE",
    "name": "DP2/Scenario/SourcePanel/target-2/exact",
    "exportName": "RawDP2ScenarioSourcePanelTarget2Exact",
    "type": "frame",
    "width": 380,
    "height": 884,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "UWEJp",
    "name": "DP/Scenario/FeaturedTopics/SideNav/exact",
    "exportName": "RawDPScenarioFeaturedTopicsSideNavExact",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": {
      "color": "#f7f9ffff",
      "enabled": false,
      "type": "color"
    },
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "aJPjG",
    "name": "DP/Scenario/FeaturedTopics/MainPanel",
    "exportName": "RawDPScenarioFeaturedTopicsMainPanel",
    "type": "frame",
    "width": 1328,
    "height": 876,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "SpL7m",
    "name": "DP/FeaturedTopics/ListRow",
    "exportName": "RawDPFeaturedTopicsListRow",
    "type": "frame",
    "width": 1268,
    "height": 54,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "k4bnX",
    "name": "DP/Scenario/FeaturedTopics/Page",
    "exportName": "RawDPScenarioFeaturedTopicsPage",
    "type": "frame",
    "width": 1600,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "o20Mj7",
    "name": "DP/Navigation/HomeSideNav/NavStage/featuredSelected",
    "exportName": "RawDPNavigationHomeSideNavNavStageFeaturedSelected",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "E4KbC8",
    "name": "DP/Navigation/HomeSideNav/NavStage/recentSelected",
    "exportName": "RawDPNavigationHomeSideNavNavStageRecentSelected",
    "type": "frame",
    "width": 260,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "tam1d",
    "name": "DP/Scenario/RecentAccess/MainPanel",
    "exportName": "RawDPScenarioRecentAccessMainPanel",
    "type": "frame",
    "width": 1328,
    "height": 876,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 20,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "I84H6G",
    "name": "DP/RecentAccess/SolidCard",
    "exportName": "RawDPRecentAccessSolidCard",
    "type": "frame",
    "width": 296,
    "height": 128,
    "fill": "#F7F8FF",
    "stroke": "#00000000",
    "strokeWidth": null,
    "cornerRadius": 14,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "KboNQ",
    "name": "DP/Scenario/RecentAccess/Page",
    "exportName": "RawDPScenarioRecentAccessPage",
    "type": "frame",
    "width": 1600,
    "height": 900,
    "fill": "#F7F9FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "y2jof",
    "name": "DP2/Studio/TopBarTitle",
    "exportName": "RawDP2StudioTopBarTitle",
    "type": "frame",
    "width": 96,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "o4fEy9",
    "name": "DP2/Button/IconOnly/calendar/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlyCalendarGhostSm",
    "type": "frame",
    "width": 28,
    "height": 28,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "Ak3wb",
    "name": "DP2/Studio/TopBarActions",
    "exportName": "RawDP2StudioTopBarActions",
    "type": "frame",
    "width": 100,
    "height": 28,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "CXyth",
    "name": "DP2/Studio/TopBar",
    "exportName": "RawDP2StudioTopBar",
    "type": "frame",
    "width": 352,
    "height": 48,
    "fill": "#FFFFFF",
    "stroke": "#2020200F",
    "strokeWidth": {
      "bottom": 1
    },
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "Johkb",
    "name": "DP2/Button/IconOnly/edit/ghost/sm",
    "exportName": "RawDP2ButtonIconOnlyEditGhostSm",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 9999,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "LukMc",
    "name": "DP2/Studio/FeatureCard",
    "exportName": "RawDP2StudioFeatureCard",
    "type": "frame",
    "width": 148,
    "height": 72,
    "fill": "#EFF0FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "i1HT35",
    "name": "DP2/Studio/FeatureGrid",
    "exportName": "RawDP2StudioFeatureGrid",
    "type": "frame",
    "width": 320,
    "height": 164,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "y9AqVF",
    "name": "DP2/Studio/RecordItem",
    "exportName": "RawDP2StudioRecordItem",
    "type": "frame",
    "width": 320,
    "height": 56,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "qmeNA",
    "name": "DP2/Studio/RecordList",
    "exportName": "RawDP2StudioRecordList",
    "type": "frame",
    "width": 320,
    "height": 128,
    "fill": null,
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "Xvd8E",
    "name": "DP2/Studio/Body",
    "exportName": "RawDP2StudioBody",
    "type": "frame",
    "width": 352,
    "height": 836,
    "fill": "#FFFFFF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "vertical",
    "slot": null
  },
  {
    "id": "zayVJ",
    "name": "DP2/Studio/FeatureCard/Summary",
    "exportName": "RawDP2StudioFeatureCardSummary",
    "type": "frame",
    "width": 148,
    "height": 72,
    "fill": "#EFF0FF",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "eGH6a",
    "name": "DP2/Studio/FeatureCard/FAQ",
    "exportName": "RawDP2StudioFeatureCardFAQ",
    "type": "frame",
    "width": 148,
    "height": 72,
    "fill": "#F3F3EA",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "P73gD",
    "name": "DP2/Studio/FeatureCard/Report",
    "exportName": "RawDP2StudioFeatureCardReport",
    "type": "frame",
    "width": 148,
    "height": 72,
    "fill": "#F2EBDC",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": 12,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "z1HU3V",
    "name": "DP2/Studio/RecordItem/Summary",
    "exportName": "RawDP2StudioRecordItemSummary",
    "type": "frame",
    "width": 320,
    "height": 56,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "vl2uw",
    "name": "DP2/Studio/RecordItem/FAQ",
    "exportName": "RawDP2StudioRecordItemFAQ",
    "type": "frame",
    "width": 320,
    "height": 56,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": null,
    "slot": null
  },
  {
    "id": "sMJPL",
    "name": "DP2/Icon/16/search",
    "exportName": "RawDP2Icon16Search",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "pB8Vm",
    "name": "DP2/Icon/16/calendar",
    "exportName": "RawDP2Icon16Calendar",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "TzLDR",
    "name": "DP2/Icon/16/panelRight",
    "exportName": "RawDP2Icon16PanelRight",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "g2YBK",
    "name": "DP2/Icon/16/pencil",
    "exportName": "RawDP2Icon16Pencil",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "OPeyZ",
    "name": "DP2/Icon/16/document",
    "exportName": "RawDP2Icon16Document",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "DhC4w",
    "name": "DP2/Icon/16/message",
    "exportName": "RawDP2Icon16Message",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "k9h6b",
    "name": "DP2/Icon/16/report",
    "exportName": "RawDP2Icon16Report",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "gWirc",
    "name": "DP2/Icon/16/square",
    "exportName": "RawDP2Icon16Square",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "P3mJz",
    "name": "DP2/Icon/16/chevronDown",
    "exportName": "RawDP2Icon16ChevronDown",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Z4qzU",
    "name": "DP2/Icon/16/arrowUp",
    "exportName": "RawDP2Icon16ArrowUp",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "wQc9c",
    "name": "DP2/Icon/16/zap",
    "exportName": "RawDP2Icon16Zap",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "KAFEv",
    "name": "DP2/Icon/16/history",
    "exportName": "RawDP2Icon16History",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "yxANx",
    "name": "DP2/Icon/16/ellipsisVertical",
    "exportName": "RawDP2Icon16EllipsisVertical",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "R5r6hf",
    "name": "DP2/Icon/20/search",
    "exportName": "RawDP2Icon20Search",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "uxsNm",
    "name": "DP2/Icon/20/calendar",
    "exportName": "RawDP2Icon20Calendar",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "BHkaH",
    "name": "DP2/Icon/20/panelRight",
    "exportName": "RawDP2Icon20PanelRight",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "sFUuk",
    "name": "DP2/Icon/20/pencil",
    "exportName": "RawDP2Icon20Pencil",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "vSYk5",
    "name": "DP2/Icon/20/document",
    "exportName": "RawDP2Icon20Document",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "UxLLZ",
    "name": "DP2/Icon/20/message",
    "exportName": "RawDP2Icon20Message",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Q0sk9C",
    "name": "DP2/Icon/20/report",
    "exportName": "RawDP2Icon20Report",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "UwIJE",
    "name": "DP2/Icon/20/square",
    "exportName": "RawDP2Icon20Square",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "ON6fi",
    "name": "DP2/Icon/20/chevronDown",
    "exportName": "RawDP2Icon20ChevronDown",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "jKaen",
    "name": "DP2/Icon/20/arrowUp",
    "exportName": "RawDP2Icon20ArrowUp",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "WYRUM",
    "name": "DP2/Icon/20/zap",
    "exportName": "RawDP2Icon20Zap",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "w91QF5",
    "name": "DP2/Icon/20/history",
    "exportName": "RawDP2Icon20History",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "bb4Uh",
    "name": "DP2/Icon/20/ellipsisVertical",
    "exportName": "RawDP2Icon20EllipsisVertical",
    "type": "frame",
    "width": 20,
    "height": 20,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "ZVMlK",
    "name": "DP2/Icon/24/search",
    "exportName": "RawDP2Icon24Search",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "KqTbA",
    "name": "DP2/Icon/24/calendar",
    "exportName": "RawDP2Icon24Calendar",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "aS6Xj",
    "name": "DP2/Icon/24/panelRight",
    "exportName": "RawDP2Icon24PanelRight",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Tk4IU",
    "name": "DP2/Icon/24/pencil",
    "exportName": "RawDP2Icon24Pencil",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "O4Bl7a",
    "name": "DP2/Icon/24/document",
    "exportName": "RawDP2Icon24Document",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "TFU7O",
    "name": "DP2/Icon/24/message",
    "exportName": "RawDP2Icon24Message",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "p2LUa",
    "name": "DP2/Icon/24/report",
    "exportName": "RawDP2Icon24Report",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "tvPwG",
    "name": "DP2/Icon/24/square",
    "exportName": "RawDP2Icon24Square",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "a8MhEu",
    "name": "DP2/Icon/24/chevronDown",
    "exportName": "RawDP2Icon24ChevronDown",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "WmLkB",
    "name": "DP2/Icon/24/arrowUp",
    "exportName": "RawDP2Icon24ArrowUp",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "TyG0S",
    "name": "DP2/Icon/24/zap",
    "exportName": "RawDP2Icon24Zap",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "PCeK2",
    "name": "DP2/Icon/24/history",
    "exportName": "RawDP2Icon24History",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "Jz9u1",
    "name": "DP2/Icon/24/ellipsisVertical",
    "exportName": "RawDP2Icon24EllipsisVertical",
    "type": "frame",
    "width": 24,
    "height": 24,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  },
  {
    "id": "iv7Kz",
    "name": "DP2/Icon/16/send",
    "exportName": "RawDP2Icon16Send",
    "type": "frame",
    "width": 16,
    "height": 16,
    "fill": "#00000000",
    "stroke": null,
    "strokeWidth": null,
    "cornerRadius": null,
    "opacity": null,
    "layout": "none",
    "slot": null
  }
] satisfies RawNodeMeta[]

export const rawNodeMap = Object.fromEntries(rawNodes.map((node) => [node.name, node])) as Record<string, RawNodeMeta>
